export const quizQuestions = [
    "You choose your applications based on aesthetics",
    "You have at least two monitors set up",
    "You're always open to trying new gadgets",
    "You're always open to trying new programs/applications",
    "You own a mechanical keyboard",
    "Your friends come to you for tech issues",
    "Your family comes to you for tech issues",
    "You Google all of your problems",
    "You go on Reddit a lot",
    "r/cscareerquestions",
    "You enjoy customising everything you own",
    "You were on the home automation bandwagon at one point",
    "Have you tried turning it off and on again?",
    "It doesn't take you long to learn how to use new tech",
    "You learn everything on Youtube",
    "Is it plugged in?",
    "You know what WWDC is 🤓",
    "Your field of study is within STEM",
    "You're open to using most social media channels",
    "You care about privacy when online"
]
