export const quizQuestions = [
    "You choose your applications based on aesthetics",
    "You have at least two monitors set up",
    "You're always open to trying new gadgets",
    "You're always trying new programs/applications",
    "You own a mechanical keyboard",
    "Your friends come to you for tech issues",
    "Your family comes to you for tech issues",
    "You Google all of your problems",
    "You go on Reddit a lot",
    "r/cscareerquestions",
    "You enjoy customising everything you own",
    "You were on the home automation bandwagon at one point",
    "Have you tried turning it off and on again?",
    "It doesn't take you long to learn how to use new tech",
    "You learn everything on Youtube",
    "Is it plugged in?",
    "You know what WWDC is 🤓",
    "Your field of study is within STEM",
    "You're open to using most social media profiles",
    "You care about privacy when online",
    "Internet speed matters",
    "You wait for shows to come out on Torrent",
    "You use Google Chrome or Firefox",
    "You think coding is useful in most jobs",
    "You check your phone all the time",
    "You own a pair of noise-cancelling headphones",
    "You work / want to work in tech",
    "Smart Glasses look dumb but you'd try it anyway",
    "You watch tech Youtubers",
    "Quarantine got you learning new things online"
]
